# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaAgregarPersonal.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaAgregarPersonal(object):
    def setupUi(self, VentanaAgregarPersonal):
        VentanaAgregarPersonal.setObjectName("VentanaAgregarPersonal")
        VentanaAgregarPersonal.resize(381, 447)
        VentanaAgregarPersonal.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.AgregarPersonalWindow = QtWidgets.QWidget(VentanaAgregarPersonal)
        self.AgregarPersonalWindow.setObjectName("AgregarPersonalWindow")
        self.label_2 = QtWidgets.QLabel(self.AgregarPersonalWindow)
        self.label_2.setGeometry(QtCore.QRect(110, 160, 171, 31))
        self.label_2.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.label_PrecioProd = QtWidgets.QLabel(self.AgregarPersonalWindow)
        self.label_PrecioProd.setGeometry(QtCore.QRect(80, 229, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_PrecioProd.setFont(font)
        self.label_PrecioProd.setObjectName("label_PrecioProd")
        self.label_DescripProd = QtWidgets.QLabel(self.AgregarPersonalWindow)
        self.label_DescripProd.setGeometry(QtCore.QRect(60, 290, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_DescripProd.setFont(font)
        self.label_DescripProd.setObjectName("label_DescripProd")
        self.lineCargoPersonal = QtWidgets.QLineEdit(self.AgregarPersonalWindow)
        self.lineCargoPersonal.setGeometry(QtCore.QRect(140, 240, 171, 20))
        self.lineCargoPersonal.setStyleSheet("font: 12pt \"Arial\";")
        self.lineCargoPersonal.setText("")
        self.lineCargoPersonal.setObjectName("lineCargoPersonal")
        self.label_CantidadProd = QtWidgets.QLabel(self.AgregarPersonalWindow)
        self.label_CantidadProd.setGeometry(QtCore.QRect(70, 260, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_CantidadProd.setFont(font)
        self.label_CantidadProd.setObjectName("label_CantidadProd")
        self.pushButton_registrar = QtWidgets.QPushButton(self.AgregarPersonalWindow)
        self.pushButton_registrar.setGeometry(QtCore.QRect(220, 350, 91, 23))
        self.pushButton_registrar.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"background-color: rgb(0, 170, 0) ;")
        self.pushButton_registrar.setObjectName("pushButton_registrar")
        self.label = QtWidgets.QLabel(self.AgregarPersonalWindow)
        self.label.setGeometry(QtCore.QRect(120, 20, 141, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Agregar.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_NombreProducto = QtWidgets.QLabel(self.AgregarPersonalWindow)
        self.label_NombreProducto.setGeometry(QtCore.QRect(70, 210, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_NombreProducto.setFont(font)
        self.label_NombreProducto.setObjectName("label_NombreProducto")
        self.pushButton_volver = QtWidgets.QPushButton(self.AgregarPersonalWindow)
        self.pushButton_volver.setGeometry(QtCore.QRect(70, 350, 75, 23))
        self.pushButton_volver.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"background-color: rgb(0, 0, 255) ;")
        self.pushButton_volver.setObjectName("pushButton_volver")
        self.lineNomPersonal = QtWidgets.QLineEdit(self.AgregarPersonalWindow)
        self.lineNomPersonal.setGeometry(QtCore.QRect(140, 210, 171, 20))
        self.lineNomPersonal.setStyleSheet("font: 12pt \"Arial\";")
        self.lineNomPersonal.setObjectName("lineNomPersonal")
        self.lineCorreoPersonal = QtWidgets.QLineEdit(self.AgregarPersonalWindow)
        self.lineCorreoPersonal.setGeometry(QtCore.QRect(140, 270, 171, 20))
        self.lineCorreoPersonal.setStyleSheet("font: 12pt \"Arial\";")
        self.lineCorreoPersonal.setText("")
        self.lineCorreoPersonal.setObjectName("lineCorreoPersonal")
        self.lineTelPersonal = QtWidgets.QLineEdit(self.AgregarPersonalWindow)
        self.lineTelPersonal.setGeometry(QtCore.QRect(140, 300, 171, 20))
        self.lineTelPersonal.setStyleSheet("font: 12pt \"Arial\";")
        self.lineTelPersonal.setText("")
        self.lineTelPersonal.setObjectName("lineTelPersonal")
        VentanaAgregarPersonal.setCentralWidget(self.AgregarPersonalWindow)
        self.menubar = QtWidgets.QMenuBar(VentanaAgregarPersonal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 381, 21))
        self.menubar.setObjectName("menubar")
        VentanaAgregarPersonal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaAgregarPersonal)
        self.statusbar.setObjectName("statusbar")
        VentanaAgregarPersonal.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaAgregarPersonal)
        QtCore.QMetaObject.connectSlotsByName(VentanaAgregarPersonal)

    def retranslateUi(self, VentanaAgregarPersonal):
        _translate = QtCore.QCoreApplication.translate
        VentanaAgregarPersonal.setWindowTitle(_translate("VentanaAgregarPersonal", "VentanaAgregarPersonal"))
        self.label_2.setText(_translate("VentanaAgregarPersonal", "Agregar Personal"))
        self.label_PrecioProd.setText(_translate("VentanaAgregarPersonal", "Cargo:"))
        self.label_DescripProd.setText(_translate("VentanaAgregarPersonal", " Teléfono:"))
        self.label_CantidadProd.setText(_translate("VentanaAgregarPersonal", " Correo:"))
        self.pushButton_registrar.setText(_translate("VentanaAgregarPersonal", "Registrar"))
        self.label_NombreProducto.setText(_translate("VentanaAgregarPersonal", "Nombre: "))
        self.pushButton_volver.setText(_translate("VentanaAgregarPersonal", "Volver"))
