# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaAgregarProducto.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaAgregarProducto(object):
    def setupUi(self, VentanaAgregarProducto):
        VentanaAgregarProducto.setObjectName("VentanaAgregarProducto")
        VentanaAgregarProducto.resize(411, 518)
        VentanaAgregarProducto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidgetProd = QtWidgets.QWidget(VentanaAgregarProducto)
        self.centralwidgetProd.setObjectName("centralwidgetProd")
        self.label = QtWidgets.QLabel(self.centralwidgetProd)
        self.label.setGeometry(QtCore.QRect(140, 20, 141, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Agregar.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidgetProd)
        self.label_2.setGeometry(QtCore.QRect(130, 160, 161, 31))
        self.label_2.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.label_NombreProducto = QtWidgets.QLabel(self.centralwidgetProd)
        self.label_NombreProducto.setGeometry(QtCore.QRect(30, 240, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_NombreProducto.setFont(font)
        self.label_NombreProducto.setObjectName("label_NombreProducto")
        self.lineNomProducto = QtWidgets.QLineEdit(self.centralwidgetProd)
        self.lineNomProducto.setGeometry(QtCore.QRect(160, 240, 171, 20))
        self.lineNomProducto.setStyleSheet("font: 12pt \"Arial\";")
        self.lineNomProducto.setObjectName("lineNomProducto")
        self.label_PrecioProd = QtWidgets.QLabel(self.centralwidgetProd)
        self.label_PrecioProd.setGeometry(QtCore.QRect(100, 270, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_PrecioProd.setFont(font)
        self.label_PrecioProd.setObjectName("label_PrecioProd")
        self.linePrecioProd = QtWidgets.QLineEdit(self.centralwidgetProd)
        self.linePrecioProd.setGeometry(QtCore.QRect(160, 270, 171, 20))
        self.linePrecioProd.setStyleSheet("font: 12pt \"Arial\";")
        self.linePrecioProd.setText("")
        self.linePrecioProd.setObjectName("linePrecioProd")
        self.label_CantidadProd = QtWidgets.QLabel(self.centralwidgetProd)
        self.label_CantidadProd.setGeometry(QtCore.QRect(80, 300, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_CantidadProd.setFont(font)
        self.label_CantidadProd.setObjectName("label_CantidadProd")
        self.spinBoxCantidad = QtWidgets.QSpinBox(self.centralwidgetProd)
        self.spinBoxCantidad.setGeometry(QtCore.QRect(160, 300, 81, 22))
        self.spinBoxCantidad.setStyleSheet("font: 12pt \"Arial\";")
        self.spinBoxCantidad.setObjectName("spinBoxCantidad")
        self.label_DescripProd = QtWidgets.QLabel(self.centralwidgetProd)
        self.label_DescripProd.setGeometry(QtCore.QRect(60, 320, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_DescripProd.setFont(font)
        self.label_DescripProd.setObjectName("label_DescripProd")
        self.lineDescripcionProd = QtWidgets.QLineEdit(self.centralwidgetProd)
        self.lineDescripcionProd.setGeometry(QtCore.QRect(160, 330, 171, 71))
        self.lineDescripcionProd.setStyleSheet("font: 12pt \"Arial\";")
        self.lineDescripcionProd.setObjectName("lineDescripcionProd")
        self.pushButton_volver = QtWidgets.QPushButton(self.centralwidgetProd)
        self.pushButton_volver.setGeometry(QtCore.QRect(80, 450, 75, 23))
        self.pushButton_volver.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"background-color: rgb(0, 0, 255) ;")
        self.pushButton_volver.setObjectName("pushButton_volver")
        self.pushButton_registrar = QtWidgets.QPushButton(self.centralwidgetProd)
        self.pushButton_registrar.setGeometry(QtCore.QRect(240, 450, 91, 23))
        self.pushButton_registrar.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"background-color: rgb(0, 170, 0) ;")
        self.pushButton_registrar.setObjectName("pushButton_registrar")
        VentanaAgregarProducto.setCentralWidget(self.centralwidgetProd)
        self.menubar = QtWidgets.QMenuBar(VentanaAgregarProducto)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 411, 21))
        self.menubar.setObjectName("menubar")
        VentanaAgregarProducto.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaAgregarProducto)
        self.statusbar.setObjectName("statusbar")
        VentanaAgregarProducto.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaAgregarProducto)
        QtCore.QMetaObject.connectSlotsByName(VentanaAgregarProducto)

    def retranslateUi(self, VentanaAgregarProducto):
        _translate = QtCore.QCoreApplication.translate
        VentanaAgregarProducto.setWindowTitle(_translate("VentanaAgregarProducto", "VentanaAgregarProducto"))
        self.label_2.setText(_translate("VentanaAgregarProducto", "Agregar Producto"))
        self.label_NombreProducto.setText(_translate("VentanaAgregarProducto", "Nombre producto: "))
        self.label_PrecioProd.setText(_translate("VentanaAgregarProducto", " Precio: "))
        self.label_CantidadProd.setText(_translate("VentanaAgregarProducto", " Cantidad: "))
        self.label_DescripProd.setText(_translate("VentanaAgregarProducto", " Descripción: "))
        self.pushButton_volver.setText(_translate("VentanaAgregarProducto", "Volver"))
        self.pushButton_registrar.setText(_translate("VentanaAgregarProducto", "Registrar"))
