# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaAgregarVenta.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaAgregarVenta(object):
    def setupUi(self, VentanaAgregarVenta):
        VentanaAgregarVenta.setObjectName("VentanaAgregarVenta")
        VentanaAgregarVenta.resize(773, 557)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VentanaAgregarVenta.sizePolicy().hasHeightForWidth())
        VentanaAgregarVenta.setSizePolicy(sizePolicy)
        VentanaAgregarVenta.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(VentanaAgregarVenta)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 140, 161, 31))
        self.label_2.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 10, 141, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Agregar.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_Date = QtWidgets.QLabel(self.centralwidget)
        self.label_Date.setGeometry(QtCore.QRect(30, 180, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_Date.setFont(font)
        self.label_Date.setObjectName("label_Date")
        self.pushButton_volver = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_volver.setGeometry(QtCore.QRect(110, 460, 75, 23))
        self.pushButton_volver.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"background-color: rgb(0, 0, 255) ;")
        self.pushButton_volver.setObjectName("pushButton_volver")
        self.LineHora = QtWidgets.QLineEdit(self.centralwidget)
        self.LineHora.setGeometry(QtCore.QRect(150, 220, 101, 20))
        self.LineHora.setStyleSheet("font: 12pt \"Arial\";")
        self.LineHora.setText("")
        self.LineHora.setObjectName("LineHora")
        self.LineFecha = QtWidgets.QLineEdit(self.centralwidget)
        self.LineFecha.setGeometry(QtCore.QRect(30, 220, 101, 20))
        self.LineFecha.setStyleSheet("font: 12pt \"Arial\";")
        self.LineFecha.setObjectName("LineFecha")
        self.spinBoxCantidad = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxCantidad.setGeometry(QtCore.QRect(110, 300, 81, 21))
        self.spinBoxCantidad.setStyleSheet("font: 12pt \"Arial\";")
        self.spinBoxCantidad.setObjectName("spinBoxCantidad")
        self.pushButton_registrar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_registrar.setGeometry(QtCore.QRect(570, 460, 121, 23))
        self.pushButton_registrar.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"background-color: rgb(0, 170, 0) ;")
        self.pushButton_registrar.setObjectName("pushButton_registrar")
        self.label_hour = QtWidgets.QLabel(self.centralwidget)
        self.label_hour.setGeometry(QtCore.QRect(150, 190, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_hour.setFont(font)
        self.label_hour.setObjectName("label_hour")
        self.label_Prod = QtWidgets.QLabel(self.centralwidget)
        self.label_Prod.setGeometry(QtCore.QRect(30, 250, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_Prod.setFont(font)
        self.label_Prod.setObjectName("label_Prod")
        self.label_Cant = QtWidgets.QLabel(self.centralwidget)
        self.label_Cant.setGeometry(QtCore.QRect(30, 290, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_Cant.setFont(font)
        self.label_Cant.setObjectName("label_Cant")
        self.comboBoxProducto = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxProducto.setGeometry(QtCore.QRect(110, 260, 141, 22))
        self.comboBoxProducto.setStyleSheet("font: 12pt \"Arial\";")
        self.comboBoxProducto.setObjectName("comboBoxProducto")
        self.tableVenta = QtWidgets.QTableWidget(self.centralwidget)
        self.tableVenta.setGeometry(QtCore.QRect(280, 190, 461, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableVenta.sizePolicy().hasHeightForWidth())
        self.tableVenta.setSizePolicy(sizePolicy)
        self.tableVenta.setMinimumSize(QtCore.QSize(461, 0))
        self.tableVenta.setMaximumSize(QtCore.QSize(461, 16777215))
        self.tableVenta.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.tableVenta.setFont(font)
        self.tableVenta.setAcceptDrops(False)
        self.tableVenta.setToolTip("")
        self.tableVenta.setWhatsThis("")
        self.tableVenta.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableVenta.setStyleSheet("font: 12pt \"Arial\";\n"
"")
        self.tableVenta.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableVenta.setObjectName("tableVenta")
        self.tableVenta.setColumnCount(4)
        self.tableVenta.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableVenta.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableVenta.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableVenta.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableVenta.setHorizontalHeaderItem(3, item)
        self.pushButton_MasProducto = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_MasProducto.setGeometry(QtCore.QRect(30, 330, 221, 41))
        self.pushButton_MasProducto.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"\n"
"    background-color:rgb(183, 229, 69);\n"
"    font: 12pt \"Arial\";\n"
"\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(0, 255, 0);\n"
"    font: 12pt \"Arial\";\n"
"\n"
"    \n"
"}")
        self.pushButton_MasProducto.setObjectName("pushButton_MasProducto")
        self.label_total = QtWidgets.QLabel(self.centralwidget)
        self.label_total.setGeometry(QtCore.QRect(490, 400, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_total.setFont(font)
        self.label_total.setStyleSheet("font: 87 16pt \"Arial Black\";")
        self.label_total.setObjectName("label_total")
        self.labelTotal = QtWidgets.QLabel(self.centralwidget)
        self.labelTotal.setGeometry(QtCore.QRect(560, 400, 131, 31))
        self.labelTotal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelTotal.setStyleSheet("font: 75 16pt \"Arial\";\n"
"background-color:rgb(183, 229, 69);")
        self.labelTotal.setObjectName("labelTotal")
        VentanaAgregarVenta.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VentanaAgregarVenta)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 773, 21))
        self.menubar.setObjectName("menubar")
        VentanaAgregarVenta.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaAgregarVenta)
        self.statusbar.setObjectName("statusbar")
        VentanaAgregarVenta.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaAgregarVenta)
        QtCore.QMetaObject.connectSlotsByName(VentanaAgregarVenta)

    def retranslateUi(self, VentanaAgregarVenta):
        _translate = QtCore.QCoreApplication.translate
        VentanaAgregarVenta.setWindowTitle(_translate("VentanaAgregarVenta", "VentanaAgregarVenta"))
        self.label_2.setText(_translate("VentanaAgregarVenta", "Agregar Venta"))
        self.label_Date.setText(_translate("VentanaAgregarVenta", "Fecha:"))
        self.pushButton_volver.setText(_translate("VentanaAgregarVenta", "Volver"))
        self.pushButton_registrar.setText(_translate("VentanaAgregarVenta", "Registrar Venta"))
        self.label_hour.setText(_translate("VentanaAgregarVenta", "Hora:"))
        self.label_Prod.setText(_translate("VentanaAgregarVenta", "Producto:"))
        self.label_Cant.setText(_translate("VentanaAgregarVenta", "Cantidad:"))
        item = self.tableVenta.horizontalHeaderItem(0)
        item.setText(_translate("VentanaAgregarVenta", "Producto"))
        item = self.tableVenta.horizontalHeaderItem(1)
        item.setText(_translate("VentanaAgregarVenta", "Precio"))
        item = self.tableVenta.horizontalHeaderItem(2)
        item.setText(_translate("VentanaAgregarVenta", "Cantidad"))
        item = self.tableVenta.horizontalHeaderItem(3)
        item.setText(_translate("VentanaAgregarVenta", "Total"))
        self.pushButton_MasProducto.setText(_translate("VentanaAgregarVenta", "Agregar otro producto"))
        self.label_total.setText(_translate("VentanaAgregarVenta", "Total:"))
        self.labelTotal.setText(_translate("VentanaAgregarVenta", "$"))
