# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaConsultarProducto.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaConsultarProducto(object):
    def setupUi(self, VentanaConsultarProducto):
        VentanaConsultarProducto.setObjectName("VentanaConsultarProducto")
        VentanaConsultarProducto.resize(521, 518)
        VentanaConsultarProducto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.VentanaConsultarProducto_2 = QtWidgets.QWidget(VentanaConsultarProducto)
        self.VentanaConsultarProducto_2.setObjectName("VentanaConsultarProducto_2")
        self.label = QtWidgets.QLabel(self.VentanaConsultarProducto_2)
        self.label.setGeometry(QtCore.QRect(210, 10, 141, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Buscar.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.VentanaConsultarProducto_2)
        self.label_2.setGeometry(QtCore.QRect(180, 150, 181, 31))
        self.label_2.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.tableConsultaProd = QtWidgets.QTableWidget(self.VentanaConsultarProducto_2)
        self.tableConsultaProd.setGeometry(QtCore.QRect(30, 200, 461, 192))
        self.tableConsultaProd.setMinimumSize(QtCore.QSize(461, 0))
        self.tableConsultaProd.setMaximumSize(QtCore.QSize(461, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.tableConsultaProd.setFont(font)
        self.tableConsultaProd.setStyleSheet("font: 12pt \"Arial\";")
        self.tableConsultaProd.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableConsultaProd.setObjectName("tableConsultaProd")
        self.tableConsultaProd.setColumnCount(4)
        self.tableConsultaProd.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableConsultaProd.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableConsultaProd.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableConsultaProd.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableConsultaProd.setHorizontalHeaderItem(3, item)
        self.pushButton_volver = QtWidgets.QPushButton(self.VentanaConsultarProducto_2)
        self.pushButton_volver.setGeometry(QtCore.QRect(240, 410, 75, 23))
        self.pushButton_volver.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"background-color: rgb(0, 0, 255) ;")
        self.pushButton_volver.setObjectName("pushButton_volver")
        VentanaConsultarProducto.setCentralWidget(self.VentanaConsultarProducto_2)
        self.menubar = QtWidgets.QMenuBar(VentanaConsultarProducto)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 521, 21))
        self.menubar.setObjectName("menubar")
        VentanaConsultarProducto.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaConsultarProducto)
        self.statusbar.setObjectName("statusbar")
        VentanaConsultarProducto.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaConsultarProducto)
        QtCore.QMetaObject.connectSlotsByName(VentanaConsultarProducto)

    def retranslateUi(self, VentanaConsultarProducto):
        _translate = QtCore.QCoreApplication.translate
        VentanaConsultarProducto.setWindowTitle(_translate("VentanaConsultarProducto", "VentanaConsultarProducto"))
        self.label_2.setText(_translate("VentanaConsultarProducto", "Consultar Productos"))
        self.tableConsultaProd.setToolTip(_translate("VentanaConsultarProducto", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.tableConsultaProd.setWhatsThis(_translate("VentanaConsultarProducto", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        item = self.tableConsultaProd.horizontalHeaderItem(0)
        item.setText(_translate("VentanaConsultarProducto", "Nombre"))
        item = self.tableConsultaProd.horizontalHeaderItem(1)
        item.setText(_translate("VentanaConsultarProducto", "Precio"))
        item = self.tableConsultaProd.horizontalHeaderItem(2)
        item.setText(_translate("VentanaConsultarProducto", "Stock"))
        item = self.tableConsultaProd.horizontalHeaderItem(3)
        item.setText(_translate("VentanaConsultarProducto", "Descripción"))
        self.pushButton_volver.setText(_translate("VentanaConsultarProducto", "Volver"))
