# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaConsultarPersonal.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaConsultarPersonal(object):
    def setupUi(self, VentanaConsultarPersonal):
        VentanaConsultarPersonal.setObjectName("VentanaConsultarPersonal")
        VentanaConsultarPersonal.resize(547, 493)
        VentanaConsultarPersonal.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ConsultarPersonalWindow = QtWidgets.QWidget(VentanaConsultarPersonal)
        self.ConsultarPersonalWindow.setObjectName("ConsultarPersonalWindow")
        self.tableConsultaPers = QtWidgets.QTableWidget(self.ConsultarPersonalWindow)
        self.tableConsultaPers.setGeometry(QtCore.QRect(40, 210, 461, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableConsultaPers.sizePolicy().hasHeightForWidth())
        self.tableConsultaPers.setSizePolicy(sizePolicy)
        self.tableConsultaPers.setMinimumSize(QtCore.QSize(461, 0))
        self.tableConsultaPers.setMaximumSize(QtCore.QSize(461, 16777215))
        self.tableConsultaPers.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.tableConsultaPers.setFont(font)
        self.tableConsultaPers.setStyleSheet("font: 12pt \"Arial\";")
        self.tableConsultaPers.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableConsultaPers.setObjectName("tableConsultaPers")
        self.tableConsultaPers.setColumnCount(4)
        self.tableConsultaPers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableConsultaPers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableConsultaPers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableConsultaPers.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableConsultaPers.setHorizontalHeaderItem(3, item)
        self.label_2 = QtWidgets.QLabel(self.ConsultarPersonalWindow)
        self.label_2.setGeometry(QtCore.QRect(190, 160, 181, 31))
        self.label_2.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.pushButton_volver = QtWidgets.QPushButton(self.ConsultarPersonalWindow)
        self.pushButton_volver.setGeometry(QtCore.QRect(250, 420, 75, 23))
        self.pushButton_volver.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"background-color: rgb(0, 0, 255) ;")
        self.pushButton_volver.setObjectName("pushButton_volver")
        self.label = QtWidgets.QLabel(self.ConsultarPersonalWindow)
        self.label.setGeometry(QtCore.QRect(220, 20, 141, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Buscar.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        VentanaConsultarPersonal.setCentralWidget(self.ConsultarPersonalWindow)
        self.menubar = QtWidgets.QMenuBar(VentanaConsultarPersonal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 547, 21))
        self.menubar.setObjectName("menubar")
        VentanaConsultarPersonal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaConsultarPersonal)
        self.statusbar.setObjectName("statusbar")
        VentanaConsultarPersonal.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaConsultarPersonal)
        QtCore.QMetaObject.connectSlotsByName(VentanaConsultarPersonal)

    def retranslateUi(self, VentanaConsultarPersonal):
        _translate = QtCore.QCoreApplication.translate
        VentanaConsultarPersonal.setWindowTitle(_translate("VentanaConsultarPersonal", "VentanaConsultarPersonal"))
        self.tableConsultaPers.setToolTip(_translate("VentanaConsultarPersonal", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.tableConsultaPers.setWhatsThis(_translate("VentanaConsultarPersonal", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        item = self.tableConsultaPers.horizontalHeaderItem(0)
        item.setText(_translate("VentanaConsultarPersonal", "Nombre"))
        item = self.tableConsultaPers.horizontalHeaderItem(1)
        item.setText(_translate("VentanaConsultarPersonal", "Cargo"))
        item = self.tableConsultaPers.horizontalHeaderItem(2)
        item.setText(_translate("VentanaConsultarPersonal", "Correo"))
        item = self.tableConsultaPers.horizontalHeaderItem(3)
        item.setText(_translate("VentanaConsultarPersonal", "Teléfono"))
        self.label_2.setText(_translate("VentanaConsultarPersonal", "Consultar Personal"))
        self.pushButton_volver.setText(_translate("VentanaConsultarPersonal", "Volver"))
