# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaEliminarPersonal.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaEliminarPersonal(object):
    def setupUi(self, VentanaEliminarPersonal):
        VentanaEliminarPersonal.setObjectName("VentanaEliminarPersonal")
        VentanaEliminarPersonal.resize(424, 474)
        VentanaEliminarPersonal.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.EliminarPersonalWindow = QtWidgets.QWidget(VentanaEliminarPersonal)
        self.EliminarPersonalWindow.setObjectName("EliminarPersonalWindow")
        self.pushButton_volver = QtWidgets.QPushButton(self.EliminarPersonalWindow)
        self.pushButton_volver.setGeometry(QtCore.QRect(80, 370, 75, 23))
        self.pushButton_volver.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"background-color: rgb(0, 0, 255) ;")
        self.pushButton_volver.setObjectName("pushButton_volver")
        self.label_ID = QtWidgets.QLabel(self.EliminarPersonalWindow)
        self.label_ID.setGeometry(QtCore.QRect(40, 210, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_ID.setFont(font)
        self.label_ID.setObjectName("label_ID")
        self.lineID = QtWidgets.QLineEdit(self.EliminarPersonalWindow)
        self.lineID.setGeometry(QtCore.QRect(140, 210, 81, 20))
        self.lineID.setStyleSheet("font: 12pt \"Arial\";")
        self.lineID.setObjectName("lineID")
        self.pushButton_buscar = QtWidgets.QPushButton(self.EliminarPersonalWindow)
        self.pushButton_buscar.setGeometry(QtCore.QRect(230, 210, 81, 23))
        self.pushButton_buscar.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 12pt \"Arial\";\n"
"background-color:rgb(255, 170, 0) ;")
        self.pushButton_buscar.setObjectName("pushButton_buscar")
        self.pushButton_eliminar = QtWidgets.QPushButton(self.EliminarPersonalWindow)
        self.pushButton_eliminar.setGeometry(QtCore.QRect(270, 370, 91, 23))
        self.pushButton_eliminar.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"background-color: rgb(255, 0, 0) ;")
        self.pushButton_eliminar.setObjectName("pushButton_eliminar")
        self.label = QtWidgets.QLabel(self.EliminarPersonalWindow)
        self.label.setGeometry(QtCore.QRect(140, 20, 141, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Eliminar.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.EliminarPersonalWindow)
        self.label_2.setGeometry(QtCore.QRect(130, 160, 171, 31))
        self.label_2.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.lineCorreoPersonal = QtWidgets.QLineEdit(self.EliminarPersonalWindow)
        self.lineCorreoPersonal.setGeometry(QtCore.QRect(140, 300, 221, 20))
        self.lineCorreoPersonal.setStyleSheet("font: 12pt \"Arial\";")
        self.lineCorreoPersonal.setText("")
        self.lineCorreoPersonal.setObjectName("lineCorreoPersonal")
        self.label_PrecioProd = QtWidgets.QLabel(self.EliminarPersonalWindow)
        self.label_PrecioProd.setGeometry(QtCore.QRect(70, 259, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_PrecioProd.setFont(font)
        self.label_PrecioProd.setObjectName("label_PrecioProd")
        self.lineCargoPersonal = QtWidgets.QLineEdit(self.EliminarPersonalWindow)
        self.lineCargoPersonal.setGeometry(QtCore.QRect(140, 270, 221, 20))
        self.lineCargoPersonal.setStyleSheet("font: 12pt \"Arial\";")
        self.lineCargoPersonal.setText("")
        self.lineCargoPersonal.setObjectName("lineCargoPersonal")
        self.lineNomPersonal = QtWidgets.QLineEdit(self.EliminarPersonalWindow)
        self.lineNomPersonal.setGeometry(QtCore.QRect(140, 240, 221, 20))
        self.lineNomPersonal.setStyleSheet("font: 12pt \"Arial\";")
        self.lineNomPersonal.setObjectName("lineNomPersonal")
        self.label_CantidadProd = QtWidgets.QLabel(self.EliminarPersonalWindow)
        self.label_CantidadProd.setGeometry(QtCore.QRect(70, 290, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_CantidadProd.setFont(font)
        self.label_CantidadProd.setObjectName("label_CantidadProd")
        self.label_NombreProducto_2 = QtWidgets.QLabel(self.EliminarPersonalWindow)
        self.label_NombreProducto_2.setGeometry(QtCore.QRect(60, 240, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_NombreProducto_2.setFont(font)
        self.label_NombreProducto_2.setObjectName("label_NombreProducto_2")
        self.lineTelefonoPersonal = QtWidgets.QLineEdit(self.EliminarPersonalWindow)
        self.lineTelefonoPersonal.setGeometry(QtCore.QRect(140, 330, 171, 21))
        self.lineTelefonoPersonal.setStyleSheet("font: 12pt \"Arial\";")
        self.lineTelefonoPersonal.setObjectName("lineTelefonoPersonal")
        self.label_DescripProd = QtWidgets.QLabel(self.EliminarPersonalWindow)
        self.label_DescripProd.setGeometry(QtCore.QRect(60, 320, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_DescripProd.setFont(font)
        self.label_DescripProd.setObjectName("label_DescripProd")
        VentanaEliminarPersonal.setCentralWidget(self.EliminarPersonalWindow)
        self.menubar = QtWidgets.QMenuBar(VentanaEliminarPersonal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 424, 21))
        self.menubar.setObjectName("menubar")
        VentanaEliminarPersonal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaEliminarPersonal)
        self.statusbar.setObjectName("statusbar")
        VentanaEliminarPersonal.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaEliminarPersonal)
        QtCore.QMetaObject.connectSlotsByName(VentanaEliminarPersonal)

    def retranslateUi(self, VentanaEliminarPersonal):
        _translate = QtCore.QCoreApplication.translate
        VentanaEliminarPersonal.setWindowTitle(_translate("VentanaEliminarPersonal", "VentanaEliminarPersonal"))
        self.pushButton_volver.setText(_translate("VentanaEliminarPersonal", "Volver"))
        self.label_ID.setText(_translate("VentanaEliminarPersonal", " ID  Producto: "))
        self.pushButton_buscar.setText(_translate("VentanaEliminarPersonal", "Buscar"))
        self.pushButton_eliminar.setText(_translate("VentanaEliminarPersonal", "Eliminar"))
        self.label_2.setText(_translate("VentanaEliminarPersonal", "Eliminar Personal"))
        self.label_PrecioProd.setText(_translate("VentanaEliminarPersonal", "   Cargo: "))
        self.label_CantidadProd.setText(_translate("VentanaEliminarPersonal", "  Correo: "))
        self.label_NombreProducto_2.setText(_translate("VentanaEliminarPersonal", "  Nombre : "))
        self.label_DescripProd.setText(_translate("VentanaEliminarPersonal", "  Teléfono: "))
