# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaEliminarProducto.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaEliminarProducto(object):
    def setupUi(self, VentanaEliminarProducto):
        VentanaEliminarProducto.setObjectName("VentanaEliminarProducto")
        VentanaEliminarProducto.resize(391, 509)
        VentanaEliminarProducto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.VentanaEliminarProducto_2 = QtWidgets.QWidget(VentanaEliminarProducto)
        self.VentanaEliminarProducto_2.setObjectName("VentanaEliminarProducto_2")
        self.label_ID = QtWidgets.QLabel(self.VentanaEliminarProducto_2)
        self.label_ID.setGeometry(QtCore.QRect(40, 210, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_ID.setFont(font)
        self.label_ID.setObjectName("label_ID")
        self.label_NombreProducto_2 = QtWidgets.QLabel(self.VentanaEliminarProducto_2)
        self.label_NombreProducto_2.setGeometry(QtCore.QRect(70, 240, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_NombreProducto_2.setFont(font)
        self.label_NombreProducto_2.setObjectName("label_NombreProducto_2")
        self.pushButton_buscar = QtWidgets.QPushButton(self.VentanaEliminarProducto_2)
        self.pushButton_buscar.setGeometry(QtCore.QRect(230, 210, 81, 23))
        self.pushButton_buscar.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 12pt \"Arial\";\n"
"background-color:rgb(255, 170, 0) ;")
        self.pushButton_buscar.setObjectName("pushButton_buscar")
        self.pushButton_volver = QtWidgets.QPushButton(self.VentanaEliminarProducto_2)
        self.pushButton_volver.setGeometry(QtCore.QRect(80, 420, 75, 23))
        self.pushButton_volver.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"background-color: rgb(0, 0, 255) ;")
        self.pushButton_volver.setObjectName("pushButton_volver")
        self.label_CantidadProd = QtWidgets.QLabel(self.VentanaEliminarProducto_2)
        self.label_CantidadProd.setGeometry(QtCore.QRect(60, 300, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_CantidadProd.setFont(font)
        self.label_CantidadProd.setObjectName("label_CantidadProd")
        self.label = QtWidgets.QLabel(self.VentanaEliminarProducto_2)
        self.label.setGeometry(QtCore.QRect(140, 20, 141, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Eliminar.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.VentanaEliminarProducto_2)
        self.label_2.setGeometry(QtCore.QRect(130, 160, 171, 31))
        self.label_2.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.label_PrecioProd = QtWidgets.QLabel(self.VentanaEliminarProducto_2)
        self.label_PrecioProd.setGeometry(QtCore.QRect(70, 270, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_PrecioProd.setFont(font)
        self.label_PrecioProd.setObjectName("label_PrecioProd")
        self.lineNomProducto = QtWidgets.QLineEdit(self.VentanaEliminarProducto_2)
        self.lineNomProducto.setGeometry(QtCore.QRect(140, 240, 171, 20))
        self.lineNomProducto.setStyleSheet("font: 12pt \"Arial\";")
        self.lineNomProducto.setObjectName("lineNomProducto")
        self.lineDescripcionProd = QtWidgets.QLineEdit(self.VentanaEliminarProducto_2)
        self.lineDescripcionProd.setGeometry(QtCore.QRect(140, 330, 171, 71))
        self.lineDescripcionProd.setStyleSheet("font: 12pt \"Arial\";")
        self.lineDescripcionProd.setObjectName("lineDescripcionProd")
        self.pushButton_eliminar = QtWidgets.QPushButton(self.VentanaEliminarProducto_2)
        self.pushButton_eliminar.setGeometry(QtCore.QRect(240, 420, 91, 23))
        self.pushButton_eliminar.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"background-color: rgb(255, 0, 0) ;")
        self.pushButton_eliminar.setObjectName("pushButton_eliminar")
        self.linePrecioProd = QtWidgets.QLineEdit(self.VentanaEliminarProducto_2)
        self.linePrecioProd.setGeometry(QtCore.QRect(140, 270, 171, 20))
        self.linePrecioProd.setStyleSheet("font: 12pt \"Arial\";")
        self.linePrecioProd.setText("")
        self.linePrecioProd.setObjectName("linePrecioProd")
        self.label_DescripProd = QtWidgets.QLabel(self.VentanaEliminarProducto_2)
        self.label_DescripProd.setGeometry(QtCore.QRect(40, 319, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_DescripProd.setFont(font)
        self.label_DescripProd.setObjectName("label_DescripProd")
        self.lineCantProd = QtWidgets.QLineEdit(self.VentanaEliminarProducto_2)
        self.lineCantProd.setGeometry(QtCore.QRect(140, 300, 171, 20))
        self.lineCantProd.setStyleSheet("font: 12pt \"Arial\";")
        self.lineCantProd.setText("")
        self.lineCantProd.setObjectName("lineCantProd")
        self.lineID = QtWidgets.QLineEdit(self.VentanaEliminarProducto_2)
        self.lineID.setGeometry(QtCore.QRect(140, 210, 81, 20))
        self.lineID.setStyleSheet("font: 12pt \"Arial\";")
        self.lineID.setObjectName("lineID")
        VentanaEliminarProducto.setCentralWidget(self.VentanaEliminarProducto_2)
        self.menubar = QtWidgets.QMenuBar(VentanaEliminarProducto)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 391, 21))
        self.menubar.setObjectName("menubar")
        VentanaEliminarProducto.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaEliminarProducto)
        self.statusbar.setObjectName("statusbar")
        VentanaEliminarProducto.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaEliminarProducto)
        QtCore.QMetaObject.connectSlotsByName(VentanaEliminarProducto)

    def retranslateUi(self, VentanaEliminarProducto):
        _translate = QtCore.QCoreApplication.translate
        VentanaEliminarProducto.setWindowTitle(_translate("VentanaEliminarProducto", "VentanaEliminarProducto"))
        self.label_ID.setText(_translate("VentanaEliminarProducto", " ID  Producto: "))
        self.label_NombreProducto_2.setText(_translate("VentanaEliminarProducto", "Nombre : "))
        self.pushButton_buscar.setText(_translate("VentanaEliminarProducto", "Buscar"))
        self.pushButton_volver.setText(_translate("VentanaEliminarProducto", "Volver"))
        self.label_CantidadProd.setText(_translate("VentanaEliminarProducto", " Cantidad: "))
        self.label_2.setText(_translate("VentanaEliminarProducto", "Eliminar Producto"))
        self.label_PrecioProd.setText(_translate("VentanaEliminarProducto", "   Precio: "))
        self.pushButton_eliminar.setText(_translate("VentanaEliminarProducto", "Eliminar"))
        self.label_DescripProd.setText(_translate("VentanaEliminarProducto", " Descripción: "))
