# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MenuCitas.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuCitas(object):
    def setupUi(self, MenuCitas):
        MenuCitas.setObjectName("MenuCitas")
        MenuCitas.resize(800, 599)
        self.centralwidget = QtWidgets.QWidget(MenuCitas)
        self.centralwidget.setObjectName("centralwidget")
        self.menuDates = QtWidgets.QLabel(self.centralwidget)
        self.menuDates.setGeometry(QtCore.QRect(0, 0, 801, 581))
        self.menuDates.setText("")
        self.menuDates.setPixmap(QtGui.QPixmap("MenuCitas.jpeg"))
        self.menuDates.setScaledContents(True)
        self.menuDates.setObjectName("menuDates")
        self.pushButton_Back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Back.setGeometry(QtCore.QRect(330, 520, 141, 31))
        self.pushButton_Back.setStyleSheet("font: 63 11pt \"Bahnschrift SemiBold\";\n"
"back-groud color: rgb(255, 255, 255);")
        self.pushButton_Back.setObjectName("pushButton_Back")
        self.pushButton_AddProducto = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_AddProducto.setGeometry(QtCore.QRect(100, 390, 121, 31))
        self.pushButton_AddProducto.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255) ;\n"
"    \n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:  rgb(85, 170, 0);\n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}")
        self.pushButton_AddProducto.setObjectName("pushButton_AddProducto")
        self.pushButton_consultProdcto = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_consultProdcto.setGeometry(QtCore.QRect(340, 390, 121, 31))
        self.pushButton_consultProdcto.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255) ;\n"
"    \n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(255, 170, 0);\n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}")
        self.pushButton_consultProdcto.setObjectName("pushButton_consultProdcto")
        self.pushButton_DeleteProducto = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_DeleteProducto.setGeometry(QtCore.QRect(570, 390, 121, 31))
        self.pushButton_DeleteProducto.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255) ;\n"
"    \n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:  rgb(255, 0, 0);\n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}")
        self.pushButton_DeleteProducto.setObjectName("pushButton_DeleteProducto")
        MenuCitas.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MenuCitas)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MenuCitas.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MenuCitas)
        self.statusbar.setObjectName("statusbar")
        MenuCitas.setStatusBar(self.statusbar)

        self.retranslateUi(MenuCitas)
        QtCore.QMetaObject.connectSlotsByName(MenuCitas)

    def retranslateUi(self, MenuCitas):
        _translate = QtCore.QCoreApplication.translate
        MenuCitas.setWindowTitle(_translate("MenuCitas", "MainWindow"))
        self.pushButton_Back.setText(_translate("MenuCitas", "Ir al menú principal"))
        self.pushButton_AddProducto.setText(_translate("MenuCitas", "Agregar"))
        self.pushButton_consultProdcto.setText(_translate("MenuCitas", "Consultar"))
        self.pushButton_DeleteProducto.setText(_translate("MenuCitas", "Eliminar"))
