# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menumascota.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menuMascota(object):
    def setupUi(self, menuMascota):
        menuMascota.setObjectName("menuMascota")
        menuMascota.resize(800, 630)
        self.centralwidget = QtWidgets.QWidget(menuMascota)
        self.centralwidget.setObjectName("centralwidget")
        self.MenuMascotas = QtWidgets.QLabel(self.centralwidget)
        self.MenuMascotas.setGeometry(QtCore.QRect(0, 0, 801, 611))
        self.MenuMascotas.setText("")
        self.MenuMascotas.setPixmap(QtGui.QPixmap("menuMasc.jpg"))
        self.MenuMascotas.setScaledContents(True)
        self.MenuMascotas.setObjectName("MenuMascotas")
        self.pushButton_AddMascota = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_AddMascota.setGeometry(QtCore.QRect(90, 320, 181, 31))
        self.pushButton_AddMascota.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255) ;\n"
"    \n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:  rgb(85, 170, 0);\n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}")
        self.pushButton_AddMascota.setObjectName("pushButton_AddMascota")
        self.pushButton_consultMascota = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_consultMascota.setGeometry(QtCore.QRect(500, 320, 181, 31))
        self.pushButton_consultMascota.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255) ;\n"
"    \n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(255, 170, 0);\n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}")
        self.pushButton_consultMascota.setObjectName("pushButton_consultMascota")
        self.pushButton_ModdifyMascota = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ModdifyMascota.setGeometry(QtCore.QRect(100, 530, 181, 31))
        self.pushButton_ModdifyMascota.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255) ;\n"
"    \n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:  rgb(85, 170, 255);\n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}")
        self.pushButton_ModdifyMascota.setObjectName("pushButton_ModdifyMascota")
        self.pushButton_DeleteMascota = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_DeleteMascota.setGeometry(QtCore.QRect(500, 530, 181, 31))
        self.pushButton_DeleteMascota.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255) ;\n"
"    \n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:  rgb(255, 0, 0);\n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}")
        self.pushButton_DeleteMascota.setObjectName("pushButton_DeleteMascota")
        self.pushButton_Back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Back.setGeometry(QtCore.QRect(330, 550, 141, 31))
        self.pushButton_Back.setStyleSheet("font: 63 11pt \"Bahnschrift SemiBold\";\n"
"back-groud color: rgb(255, 255, 255);")
        self.pushButton_Back.setObjectName("pushButton_Back")
        menuMascota.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(menuMascota)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        menuMascota.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(menuMascota)
        self.statusbar.setObjectName("statusbar")
        menuMascota.setStatusBar(self.statusbar)

        self.retranslateUi(menuMascota)
        QtCore.QMetaObject.connectSlotsByName(menuMascota)

    def retranslateUi(self, menuMascota):
        _translate = QtCore.QCoreApplication.translate
        menuMascota.setWindowTitle(_translate("menuMascota", "MainWindow"))
        self.pushButton_AddMascota.setText(_translate("menuMascota", "Agregar"))
        self.pushButton_consultMascota.setText(_translate("menuMascota", "Consultar"))
        self.pushButton_ModdifyMascota.setText(_translate("menuMascota", "Modificar"))
        self.pushButton_DeleteMascota.setText(_translate("menuMascota", "Eliminar"))
        self.pushButton_Back.setText(_translate("menuMascota", "Ir al menú principal"))
