# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MenuPersonal.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuPersonal(object):
    def setupUi(self, MenuPersonal):
        MenuPersonal.setObjectName("MenuPersonal")
        MenuPersonal.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MenuPersonal)
        self.centralwidget.setObjectName("centralwidget")
        self.mainpersonal = QtWidgets.QLabel(self.centralwidget)
        self.mainpersonal.setGeometry(QtCore.QRect(0, 0, 801, 571))
        self.mainpersonal.setText("")
        self.mainpersonal.setPixmap(QtGui.QPixmap("MenuPersonal.png"))
        self.mainpersonal.setScaledContents(True)
        self.mainpersonal.setObjectName("mainpersonal")
        self.pushButton_Back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Back.setGeometry(QtCore.QRect(330, 530, 141, 31))
        self.pushButton_Back.setStyleSheet("font: 63 11pt \"Bahnschrift SemiBold\";\n"
"back-groud color: rgb(255, 255, 255);")
        self.pushButton_Back.setObjectName("pushButton_Back")
        self.pushButton_Add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Add.setGeometry(QtCore.QRect(100, 310, 181, 31))
        self.pushButton_Add.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255) ;\n"
"    \n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:  rgb(85, 170, 0);\n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}")
        self.pushButton_Add.setObjectName("pushButton_Add")
        self.pushButton_Moddify = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Moddify.setGeometry(QtCore.QRect(100, 510, 181, 31))
        self.pushButton_Moddify.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255) ;\n"
"    \n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:  rgb(85, 170, 255);\n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}")
        self.pushButton_Moddify.setObjectName("pushButton_Moddify")
        self.pushButton_consult = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_consult.setGeometry(QtCore.QRect(500, 310, 181, 31))
        self.pushButton_consult.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255) ;\n"
"    \n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(255, 170, 0);\n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}")
        self.pushButton_consult.setObjectName("pushButton_consult")
        self.pushButton_Delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Delete.setGeometry(QtCore.QRect(510, 510, 181, 31))
        self.pushButton_Delete.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255) ;\n"
"    \n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:  rgb(255, 0, 0);\n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}")
        self.pushButton_Delete.setObjectName("pushButton_Delete")
        MenuPersonal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MenuPersonal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MenuPersonal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MenuPersonal)
        self.statusbar.setObjectName("statusbar")
        MenuPersonal.setStatusBar(self.statusbar)

        self.retranslateUi(MenuPersonal)
        QtCore.QMetaObject.connectSlotsByName(MenuPersonal)

    def retranslateUi(self, MenuPersonal):
        _translate = QtCore.QCoreApplication.translate
        MenuPersonal.setWindowTitle(_translate("MenuPersonal", "MenuPersonal"))
        self.pushButton_Back.setText(_translate("MenuPersonal", "Ir al menú principal"))
        self.pushButton_Add.setText(_translate("MenuPersonal", "Agregar "))
        self.pushButton_Moddify.setText(_translate("MenuPersonal", "Modificar"))
        self.pushButton_consult.setText(_translate("MenuPersonal", "Consultar"))
        self.pushButton_Delete.setText(_translate("MenuPersonal", "Eliminar"))
