# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menuproducts.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 651)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 621))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("menuproductos.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_AddProducto = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_AddProducto.setGeometry(QtCore.QRect(100, 350, 181, 31))
        self.pushButton_AddProducto.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255) ;\n"
"    \n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:  rgb(85, 170, 0);\n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}")
        self.pushButton_AddProducto.setObjectName("pushButton_AddProducto")
        self.pushButton_ModdifyProducto = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ModdifyProducto.setGeometry(QtCore.QRect(100, 550, 181, 31))
        self.pushButton_ModdifyProducto.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255) ;\n"
"    \n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:  rgb(85, 170, 255);\n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}")
        self.pushButton_ModdifyProducto.setObjectName("pushButton_ModdifyProducto")
        self.pushButton_consultProdcto = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_consultProdcto.setGeometry(QtCore.QRect(500, 350, 181, 31))
        self.pushButton_consultProdcto.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255) ;\n"
"    \n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(255, 170, 0);\n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}")
        self.pushButton_consultProdcto.setObjectName("pushButton_consultProdcto")
        self.pushButton_DeleteProducto = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_DeleteProducto.setGeometry(QtCore.QRect(510, 550, 181, 31))
        self.pushButton_DeleteProducto.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255) ;\n"
"    \n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:  rgb(255, 0, 0);\n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}")
        self.pushButton_DeleteProducto.setObjectName("pushButton_DeleteProducto")
        self.pushButton_Back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Back.setGeometry(QtCore.QRect(330, 580, 141, 31))
        self.pushButton_Back.setStyleSheet("font: 63 11pt \"Bahnschrift SemiBold\";\n"
"back-groud color: rgb(255, 255, 255);")
        self.pushButton_Back.setObjectName("pushButton_Back")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_AddProducto.setText(_translate("MainWindow", "Agregar "))
        self.pushButton_ModdifyProducto.setText(_translate("MainWindow", "Modificar"))
        self.pushButton_consultProdcto.setText(_translate("MainWindow", "Consultar"))
        self.pushButton_DeleteProducto.setText(_translate("MainWindow", "Eliminar"))
        self.pushButton_Back.setText(_translate("MainWindow", "Ir al menú principal"))
