# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MenuVentas.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuVentas(object):
    def setupUi(self, MenuVentas):
        MenuVentas.setObjectName("MenuVentas")
        MenuVentas.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MenuVentas)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 581))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Ventas.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_AddVenta = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_AddVenta.setGeometry(QtCore.QRect(70, 400, 181, 31))
        self.pushButton_AddVenta.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255) ;\n"
"    \n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:  rgb(85, 170, 0);\n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}")
        self.pushButton_AddVenta.setObjectName("pushButton_AddVenta")
        self.pushButton_consultVenta = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_consultVenta.setGeometry(QtCore.QRect(320, 400, 181, 31))
        self.pushButton_consultVenta.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255) ;\n"
"    \n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(255, 170, 0);\n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}")
        self.pushButton_consultVenta.setObjectName("pushButton_consultVenta")
        self.pushButton_ReportVentas = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ReportVentas.setGeometry(QtCore.QRect(560, 400, 181, 31))
        self.pushButton_ReportVentas.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255) ;\n"
"    \n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:rgb(255, 255, 0);\n"
"    font: 63 11pt \"Bahnschrift SemiBold\";\n"
"    \n"
"}")
        self.pushButton_ReportVentas.setObjectName("pushButton_ReportVentas")
        self.pushButton_Back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Back.setGeometry(QtCore.QRect(350, 520, 141, 31))
        self.pushButton_Back.setStyleSheet("font: 63 11pt \"Bahnschrift SemiBold\";\n"
"back-groud color: rgb(255, 255, 255);")
        self.pushButton_Back.setObjectName("pushButton_Back")
        MenuVentas.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MenuVentas)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MenuVentas.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MenuVentas)
        self.statusbar.setObjectName("statusbar")
        MenuVentas.setStatusBar(self.statusbar)

        self.retranslateUi(MenuVentas)
        QtCore.QMetaObject.connectSlotsByName(MenuVentas)

    def retranslateUi(self, MenuVentas):
        _translate = QtCore.QCoreApplication.translate
        MenuVentas.setWindowTitle(_translate("MenuVentas", "MenuVentas"))
        self.pushButton_AddVenta.setText(_translate("MenuVentas", "Registrar"))
        self.pushButton_consultVenta.setText(_translate("MenuVentas", "Consultar "))
        self.pushButton_ReportVentas.setText(_translate("MenuVentas", "Reporte de Ventas"))
        self.pushButton_Back.setText(_translate("MenuVentas", "Ir al menú principal"))
