# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaModificarPersonal.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaModificarPersonal(object):
    def setupUi(self, VentanaModificarPersonal):
        VentanaModificarPersonal.setObjectName("VentanaModificarPersonal")
        VentanaModificarPersonal.resize(423, 473)
        VentanaModificarPersonal.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ModificarPersonalWindow = QtWidgets.QWidget(VentanaModificarPersonal)
        self.ModificarPersonalWindow.setObjectName("ModificarPersonalWindow")
        self.label_PrecioProd = QtWidgets.QLabel(self.ModificarPersonalWindow)
        self.label_PrecioProd.setGeometry(QtCore.QRect(70, 249, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_PrecioProd.setFont(font)
        self.label_PrecioProd.setObjectName("label_PrecioProd")
        self.label = QtWidgets.QLabel(self.ModificarPersonalWindow)
        self.label.setGeometry(QtCore.QRect(140, 10, 141, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Editar.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_buscar = QtWidgets.QPushButton(self.ModificarPersonalWindow)
        self.pushButton_buscar.setGeometry(QtCore.QRect(240, 200, 71, 23))
        self.pushButton_buscar.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 12pt \"Arial\";\n"
"background-color:rgb(255, 170, 0) ;")
        self.pushButton_buscar.setObjectName("pushButton_buscar")
        self.label_CantidadProd = QtWidgets.QLabel(self.ModificarPersonalWindow)
        self.label_CantidadProd.setGeometry(QtCore.QRect(70, 280, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_CantidadProd.setFont(font)
        self.label_CantidadProd.setObjectName("label_CantidadProd")
        self.label_NombreProducto_2 = QtWidgets.QLabel(self.ModificarPersonalWindow)
        self.label_NombreProducto_2.setGeometry(QtCore.QRect(60, 230, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_NombreProducto_2.setFont(font)
        self.label_NombreProducto_2.setObjectName("label_NombreProducto_2")
        self.lineCorreoPersonal = QtWidgets.QLineEdit(self.ModificarPersonalWindow)
        self.lineCorreoPersonal.setGeometry(QtCore.QRect(140, 290, 221, 20))
        self.lineCorreoPersonal.setStyleSheet("font: 12pt \"Arial\";")
        self.lineCorreoPersonal.setText("")
        self.lineCorreoPersonal.setObjectName("lineCorreoPersonal")
        self.lineTelefonoPersonal = QtWidgets.QLineEdit(self.ModificarPersonalWindow)
        self.lineTelefonoPersonal.setGeometry(QtCore.QRect(140, 320, 171, 21))
        self.lineTelefonoPersonal.setStyleSheet("font: 12pt \"Arial\";")
        self.lineTelefonoPersonal.setObjectName("lineTelefonoPersonal")
        self.label_ID = QtWidgets.QLabel(self.ModificarPersonalWindow)
        self.label_ID.setGeometry(QtCore.QRect(40, 200, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_ID.setFont(font)
        self.label_ID.setObjectName("label_ID")
        self.label_2 = QtWidgets.QLabel(self.ModificarPersonalWindow)
        self.label_2.setGeometry(QtCore.QRect(130, 150, 171, 31))
        self.label_2.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.lineID = QtWidgets.QLineEdit(self.ModificarPersonalWindow)
        self.lineID.setGeometry(QtCore.QRect(140, 200, 91, 20))
        self.lineID.setStyleSheet("font: 12pt \"Arial\";")
        self.lineID.setObjectName("lineID")
        self.lineCargoPersonal = QtWidgets.QLineEdit(self.ModificarPersonalWindow)
        self.lineCargoPersonal.setGeometry(QtCore.QRect(140, 260, 221, 20))
        self.lineCargoPersonal.setStyleSheet("font: 12pt \"Arial\";")
        self.lineCargoPersonal.setText("")
        self.lineCargoPersonal.setObjectName("lineCargoPersonal")
        self.label_DescripProd = QtWidgets.QLabel(self.ModificarPersonalWindow)
        self.label_DescripProd.setGeometry(QtCore.QRect(60, 310, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_DescripProd.setFont(font)
        self.label_DescripProd.setObjectName("label_DescripProd")
        self.lineNomPersonal = QtWidgets.QLineEdit(self.ModificarPersonalWindow)
        self.lineNomPersonal.setGeometry(QtCore.QRect(140, 230, 221, 20))
        self.lineNomPersonal.setStyleSheet("font: 12pt \"Arial\";")
        self.lineNomPersonal.setObjectName("lineNomPersonal")
        self.pushButton_modificar = QtWidgets.QPushButton(self.ModificarPersonalWindow)
        self.pushButton_modificar.setGeometry(QtCore.QRect(270, 370, 91, 23))
        self.pushButton_modificar.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"background-color: rgb(255, 0, 0) ;")
        self.pushButton_modificar.setObjectName("pushButton_modificar")
        self.pushButton_volver = QtWidgets.QPushButton(self.ModificarPersonalWindow)
        self.pushButton_volver.setGeometry(QtCore.QRect(70, 370, 75, 23))
        self.pushButton_volver.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"background-color: rgb(0, 0, 255) ;")
        self.pushButton_volver.setObjectName("pushButton_volver")
        VentanaModificarPersonal.setCentralWidget(self.ModificarPersonalWindow)
        self.menubar = QtWidgets.QMenuBar(VentanaModificarPersonal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 423, 21))
        self.menubar.setObjectName("menubar")
        VentanaModificarPersonal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaModificarPersonal)
        self.statusbar.setObjectName("statusbar")
        VentanaModificarPersonal.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaModificarPersonal)
        QtCore.QMetaObject.connectSlotsByName(VentanaModificarPersonal)

    def retranslateUi(self, VentanaModificarPersonal):
        _translate = QtCore.QCoreApplication.translate
        VentanaModificarPersonal.setWindowTitle(_translate("VentanaModificarPersonal", "VentanaModificarPersonal"))
        self.label_PrecioProd.setText(_translate("VentanaModificarPersonal", "   Cargo: "))
        self.pushButton_buscar.setText(_translate("VentanaModificarPersonal", "Buscar"))
        self.label_CantidadProd.setText(_translate("VentanaModificarPersonal", "  Correo: "))
        self.label_NombreProducto_2.setText(_translate("VentanaModificarPersonal", "  Nombre : "))
        self.label_ID.setText(_translate("VentanaModificarPersonal", "  ID Personal: "))
        self.label_2.setText(_translate("VentanaModificarPersonal", "Modificar Personal"))
        self.label_DescripProd.setText(_translate("VentanaModificarPersonal", "  Teléfono: "))
        self.pushButton_modificar.setText(_translate("VentanaModificarPersonal", "Modificar"))
        self.pushButton_volver.setText(_translate("VentanaModificarPersonal", "Volver"))
