# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaModificarProducto.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaModificarProd(object):
    def setupUi(self, VentanaModificarProd):
        VentanaModificarProd.setObjectName("VentanaModificarProd")
        VentanaModificarProd.resize(415, 554)
        VentanaModificarProd.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.VentanaModificarProd_2 = QtWidgets.QWidget(VentanaModificarProd)
        self.VentanaModificarProd_2.setObjectName("VentanaModificarProd_2")
        self.label = QtWidgets.QLabel(self.VentanaModificarProd_2)
        self.label.setGeometry(QtCore.QRect(150, 20, 141, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Editar.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.VentanaModificarProd_2)
        self.label_2.setGeometry(QtCore.QRect(140, 160, 171, 31))
        self.label_2.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.label_ID = QtWidgets.QLabel(self.VentanaModificarProd_2)
        self.label_ID.setGeometry(QtCore.QRect(50, 210, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_ID.setFont(font)
        self.label_ID.setObjectName("label_ID")
        self.pushButton_buscar = QtWidgets.QPushButton(self.VentanaModificarProd_2)
        self.pushButton_buscar.setGeometry(QtCore.QRect(250, 210, 71, 23))
        self.pushButton_buscar.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 12pt \"Arial\";\n"
"background-color:rgb(255, 170, 0) ;")
        self.pushButton_buscar.setObjectName("pushButton_buscar")
        self.label_NombreProducto_2 = QtWidgets.QLabel(self.VentanaModificarProd_2)
        self.label_NombreProducto_2.setGeometry(QtCore.QRect(80, 240, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_NombreProducto_2.setFont(font)
        self.label_NombreProducto_2.setObjectName("label_NombreProducto_2")
        self.linePrecioProd = QtWidgets.QLineEdit(self.VentanaModificarProd_2)
        self.linePrecioProd.setGeometry(QtCore.QRect(150, 270, 171, 20))
        self.linePrecioProd.setStyleSheet("font: 12pt \"Arial\";")
        self.linePrecioProd.setText("")
        self.linePrecioProd.setObjectName("linePrecioProd")
        self.label_CantidadProd = QtWidgets.QLabel(self.VentanaModificarProd_2)
        self.label_CantidadProd.setGeometry(QtCore.QRect(70, 300, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_CantidadProd.setFont(font)
        self.label_CantidadProd.setObjectName("label_CantidadProd")
        self.label_PrecioProd = QtWidgets.QLabel(self.VentanaModificarProd_2)
        self.label_PrecioProd.setGeometry(QtCore.QRect(80, 270, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_PrecioProd.setFont(font)
        self.label_PrecioProd.setObjectName("label_PrecioProd")
        self.lineDescripcionProd = QtWidgets.QLineEdit(self.VentanaModificarProd_2)
        self.lineDescripcionProd.setGeometry(QtCore.QRect(150, 330, 171, 71))
        self.lineDescripcionProd.setStyleSheet("font: 12pt \"Arial\";")
        self.lineDescripcionProd.setObjectName("lineDescripcionProd")
        self.lineNomProducto = QtWidgets.QLineEdit(self.VentanaModificarProd_2)
        self.lineNomProducto.setGeometry(QtCore.QRect(150, 240, 171, 20))
        self.lineNomProducto.setStyleSheet("font: 12pt \"Arial\";")
        self.lineNomProducto.setObjectName("lineNomProducto")
        self.label_DescripProd = QtWidgets.QLabel(self.VentanaModificarProd_2)
        self.label_DescripProd.setGeometry(QtCore.QRect(50, 319, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_DescripProd.setFont(font)
        self.label_DescripProd.setObjectName("label_DescripProd")
        self.pushButton_volver = QtWidgets.QPushButton(self.VentanaModificarProd_2)
        self.pushButton_volver.setGeometry(QtCore.QRect(100, 420, 75, 23))
        self.pushButton_volver.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"background-color: rgb(0, 0, 255) ;")
        self.pushButton_volver.setObjectName("pushButton_volver")
        self.pushButton_modificar = QtWidgets.QPushButton(self.VentanaModificarProd_2)
        self.pushButton_modificar.setGeometry(QtCore.QRect(260, 420, 91, 23))
        self.pushButton_modificar.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"background-color: rgb(255, 0, 0) ;")
        self.pushButton_modificar.setObjectName("pushButton_modificar")
        self.lineCantProd = QtWidgets.QLineEdit(self.VentanaModificarProd_2)
        self.lineCantProd.setGeometry(QtCore.QRect(150, 300, 171, 20))
        self.lineCantProd.setStyleSheet("font: 12pt \"Arial\";")
        self.lineCantProd.setText("")
        self.lineCantProd.setObjectName("lineCantProd")
        self.lineID = QtWidgets.QLineEdit(self.VentanaModificarProd_2)
        self.lineID.setGeometry(QtCore.QRect(150, 210, 91, 20))
        self.lineID.setStyleSheet("font: 12pt \"Arial\";")
        self.lineID.setObjectName("lineID")
        VentanaModificarProd.setCentralWidget(self.VentanaModificarProd_2)
        self.menubar = QtWidgets.QMenuBar(VentanaModificarProd)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 415, 21))
        self.menubar.setObjectName("menubar")
        VentanaModificarProd.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaModificarProd)
        self.statusbar.setObjectName("statusbar")
        VentanaModificarProd.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaModificarProd)
        QtCore.QMetaObject.connectSlotsByName(VentanaModificarProd)

    def retranslateUi(self, VentanaModificarProd):
        _translate = QtCore.QCoreApplication.translate
        VentanaModificarProd.setWindowTitle(_translate("VentanaModificarProd", "VentanaModificarProd"))
        self.label_2.setText(_translate("VentanaModificarProd", "Modificar Producto"))
        self.label_ID.setText(_translate("VentanaModificarProd", "  ID Producto: "))
        self.pushButton_buscar.setText(_translate("VentanaModificarProd", "Buscar"))
        self.label_NombreProducto_2.setText(_translate("VentanaModificarProd", "Nombre : "))
        self.label_CantidadProd.setText(_translate("VentanaModificarProd", " Cantidad: "))
        self.label_PrecioProd.setText(_translate("VentanaModificarProd", "   Precio: "))
        self.label_DescripProd.setText(_translate("VentanaModificarProd", " Descripción: "))
        self.pushButton_volver.setText(_translate("VentanaModificarProd", "Volver"))
        self.pushButton_modificar.setText(_translate("VentanaModificarProd", "Modificar"))
